"""Bindings to the original RQMoE/RecBole project."""

from __future__ import annotations

import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
RUNNING_ROOT = REPOSITORY_ROOT / "exps" / "running"
for import_root in (REPOSITORY_ROOT, RUNNING_ROOT):
    if str(import_root) not in sys.path:
        sys.path.insert(0, str(import_root))

from models.Switch import DeepFM_MoE, SparseMoE  # noqa: E402
from recbole.config import Config  # noqa: E402
from recbole.data import create_dataset, data_preparation  # noqa: E402
from recbole.utils import init_seed  # noqa: E402


def use_local_atomic_data_path(config: Config) -> Config:
    """Honor the resolved local atomic-data directory saved by our runners."""
    atomic_data_path = config["atomic_data_path"]
    if atomic_data_path:
        config["data_path"] = str(Path(atomic_data_path).expanduser().resolve())
    return config


def build_deepfm_moe(config: Config, dataset):
    """Build the legacy model with an explicitly configured expert count.

    The restored ``models.Switch.DeepFM_MoE`` hard-codes four experts even
    though the manuscript fixes the total expert count at eight. Historical
    configs without ``num_experts`` retain the legacy four-expert layout;
    configs generated by the additional experiment record the intended count.
    """
    model = DeepFM_MoE(config, dataset, item_freq_tensor=None)
    configured_num_experts = config["num_experts"]
    if configured_num_experts is None:
        return model

    num_experts = int(configured_num_experts)
    top_k = int(config["top_k"])
    if num_experts < 1:
        raise ValueError("num_experts must be positive.")
    if top_k < 1 or top_k > num_experts:
        raise ValueError(f"top_k={top_k} must lie in [1, {num_experts}].")
    if model.moe_layers.num_experts == num_experts:
        return model

    legacy_moe = model.moe_layers
    model.moe_layers = SparseMoE(
        input_size=legacy_moe.input_size,
        output_size=legacy_moe.output_size,
        num_experts=num_experts,
        top_k_eval=top_k,
        hidden_sizes=[32],
        dropout=model.dropout_prob,
    )
    model.moe_layers.apply(model._init_weights)
    return model


__all__ = [
    "Config",
    "DeepFM_MoE",
    "REPOSITORY_ROOT",
    "build_deepfm_moe",
    "create_dataset",
    "data_preparation",
    "init_seed",
    "use_local_atomic_data_path",
]
